version: "3"
services:
  app:
    build: .
    environment:
      - LINEAPI_ACCESS_TOKEN
      - LINEAPI_CHANNEL_SECRET
      - OPENAI_API_KEY
    volumes:
      - .:/src
    ports:
      - 8080:8080
