[tool.poetry]
name = "gpt-love"
version = "0.1.0"
description = ""
authors = ["konumaru <konumaru1022@gmail.com>"]
readme = "README.md"
packages = [{include = "gpt_love"}]

[tool.poetry.dependencies]
python = "3.10.8"
flask = "^2.2.3"
line-bot-sdk = "^2.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
